# Generated by Django 2.1.2 on 2018-11-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024, verbose_name='Url')),
                ('normalized_path', models.CharField(blank=True, max_length=1024, verbose_name='Normalized path')),
                ('title', models.TextField(max_length=512, verbose_name='Title')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='Published at')),
                ('author', models.TextField(blank=True, max_length=128, verbose_name='Author')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='Description')),
                ('image_url', models.URLField(blank=True, max_length=1024, verbose_name='Image url')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Source',
            },
        ),
        migrations.CreateModel(
            name='NewsSourceModel',
            fields=[
                ('domain', models.CharField(max_length=253, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Source',
            },
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.NewsSourceModel'),
        ),
        migrations.AlterUniqueTogether(
            name='newsmodel',
            unique_together={('source', 'normalized_path', 'title')},
        ),
    ]
